name: Build and push image to Docker Hub

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: 
  push:
    branches: [main]
  pull_requests:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  checkout:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 
      - name: Build Docker image
        run: docker build -t whiskeymikey/zse-web:latest .