name: Build and push image to Docker Hub

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: 
  push:
    tags: [ "releases/[1-9]+.[0-9]+.[0-9]+" ]
    # branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Extract release tag
        run: IFS='/' read -r -a rel <<< ${{ github.ref }}; echo "RELEASE_TAG=${rel[-1]}" >> $GITHUB_ENV;  
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/zse-web:${{ env.RELEASE_TAG }} ${{ secrets.DOCKERHUB_USERNAME }}/zse-web:latest .
      - name: Login into Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/zse-web:${{ env.RELEASE_TAG }} 
 